SET(CMAKE_SYSTEM_NAME Linux)

SET(OWRT_STAGING_DIR /home/petr/testing/openwrt/staging_dir)
SET(OWRT_TARGET target-aarch64_cortex-a72_musl)
SET(OWRT_TOOLCHAIN toolchain-aarch64_cortex-a72_gcc-7.4.0_musl)
SET(OWRT_CROSS ${OWRT_STAGING_DIR}/${OWRT_TOOLCHAIN}/bin/aarch64-openwrt-linux-)

SET(CMAKE_C_COMPILER ${OWRT_CROSS}gcc)
SET(CMAKE_CXX_COMPILER ${OWRT_CROSS}g++)

SET(CMAKE_FIND_ROOT_PATH ${OWRT_STAGING_DIR}/${OWRT_TARGET})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

ADD_DEFINITIONS()
